cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR was not provided")
endif()

file(READ "${SOURCE_DIR}/VERSION" version_text)
string(STRIP "${version_text}" version_text)
if(NOT version_text STREQUAL "0.3.0-dev")
    message(FATAL_ERROR "VERSION must describe the 0.3.0 development release")
endif()

file(READ "${SOURCE_DIR}/CMakeLists.txt" cmake_text)
file(READ "${SOURCE_DIR}/README.md" readme_text)
file(READ "${SOURCE_DIR}/PROJECT_CONTEXT.md" context_text)
file(READ "${SOURCE_DIR}/scripts/package_release.ps1" package_text)
file(READ "${SOURCE_DIR}/build.ps1" build_text)

if(NOT cmake_text MATCHES "project\\(PiInput VERSION 0\\.3\\.0 LANGUAGES CXX\\)")
    message(FATAL_ERROR "CMake project version must be 0.3.0")
endif()
if(NOT readme_text MATCHES "当前开发版本：`v0\\.3\\.0-dev`")
    message(FATAL_ERROR "README current development version is stale")
endif()
if(NOT context_text MATCHES "v0\\.3\\.0-dev 当前实现状态")
    message(FATAL_ERROR "PROJECT_CONTEXT current implementation version is stale")
endif()
if(NOT package_text MATCHES "Get-Content .*VERSION" OR NOT package_text MATCHES "piinput-v\\$Version\\.zip")
    message(FATAL_ERROR "Release package default must derive piinput-v<version>.zip from VERSION")
endif()
if(NOT build_text MATCHES "PiInput-Install\\.exe")
    message(FATAL_ERROR "Build artifact verification must require PiInput-Install.exe")
endif()
if(NOT build_text MATCHES "legacyCompact" OR NOT build_text MATCHES "Legacy Release artifact")
    message(FATAL_ERROR "Build artifact verification must reject legacy Release files")
endif()

message(STATUS "Release metadata regression check passed")
