if(NOT DEFINED PIINPUT_SOURCE_DIR)
    message(FATAL_ERROR "PIINPUT_SOURCE_DIR was not provided")
endif()

file(READ "${PIINPUT_SOURCE_DIR}/CMakeLists.txt" cmake_text)
file(READ "${PIINPUT_SOURCE_DIR}/platform/windows/tsf/profile_tool.cpp" profile_text)
file(READ "${PIINPUT_SOURCE_DIR}/platform/windows/tsf/profile_registration.h" registration_text)
file(READ "${PIINPUT_SOURCE_DIR}/platform/windows/tsf/dllmain.cpp" dllmain_text)
file(READ "${PIINPUT_SOURCE_DIR}/repair-registration.ps1" repair_text)
file(READ "${PIINPUT_SOURCE_DIR}/refresh-installed-dev.ps1" refresh_text)
file(READ "${PIINPUT_SOURCE_DIR}/uninstall-dev.ps1" uninstall_text)
file(READ "${PIINPUT_SOURCE_DIR}/scripts/windows/resolve-installed-dev.ps1" resolver_text)
file(READ "${PIINPUT_SOURCE_DIR}/install-dev.ps1" install_text)
file(READ "${PIINPUT_SOURCE_DIR}/setup-dev.ps1" setup_text)
file(READ "${PIINPUT_SOURCE_DIR}/platform/windows/tsf/text_service.cpp" text_service_text)
file(READ "${PIINPUT_SOURCE_DIR}/platform/windows/tsf/candidate_window.cpp" candidate_window_text)

if(NOT EXISTS "${PIINPUT_SOURCE_DIR}/platform/windows/installer/main.cpp")
    message(FATAL_ERROR "Native PiInput installer source is missing")
endif()
file(READ "${PIINPUT_SOURCE_DIR}/platform/windows/installer/main.cpp" installer_text)
file(READ "${PIINPUT_SOURCE_DIR}/platform/windows/installer/install_layout.cpp" installer_layout_text)

if(cmake_text MATCHES "target_link_libraries\\(PiInputTSF[^\\)]*msctf")
    message(FATAL_ERROR "PiInputTSF must not link a non-existent msctf import library")
endif()

if(cmake_text MATCHES "target_link_libraries\\(piinput-profile[^\\)]*msctf")
    message(FATAL_ERROR "piinput-profile must not link a non-existent msctf import library")
endif()

if(profile_text MATCHES "CLSID_TF_InputProcessorProfileMgr")
    message(FATAL_ERROR "CLSID_TF_InputProcessorProfileMgr is not a Windows SDK COM class")
endif()

if(NOT registration_text MATCHES "CLSID_TF_InputProcessorProfiles")
    message(FATAL_ERROR "Profile manager creation must use CLSID_TF_InputProcessorProfiles")
endif()

if(NOT registration_text MATCHES "QueryInterface\\(IID_PPV_ARGS\\(manager\\)\\)")
    message(FATAL_ERROR "Profile manager should be obtained by querying CLSID_TF_InputProcessorProfiles")
endif()

if(NOT registration_text MATCHES "RegisterProfile\\(")
    message(FATAL_ERROR "Modern TSF registration must use ITfInputProcessorProfileMgr::RegisterProfile")
endif()

if(NOT registration_text MATCHES "TRUE,[\r\n ]*0U\\);")
    message(FATAL_ERROR "PiInput profile must be enabled by default and visible in Settings")
endif()

if(NOT profile_text MATCHES "--status")
    message(FATAL_ERROR "Profile tool must expose a machine-readable status command")
endif()

if(NOT profile_text MATCHES "result == S_FALSE")
    message(FATAL_ERROR "Idempotent deactivate/unregister must accept an absent profile")
endif()

if(NOT dllmain_text MATCHES "register_profile\\(")
    message(FATAL_ERROR "DllRegisterServer must use the shared profile registration helper")
endif()

if(NOT repair_text MATCHES "Invoke-NativeBestEffort")
    message(FATAL_ERROR "Repair script must tolerate an absent or inactive previous profile")
endif()

if(NOT repair_text MATCHES "--register")
    message(FATAL_ERROR "Repair script must explicitly register the profile before activation")
endif()

if(NOT repair_text MATCHES "--status")
    message(FATAL_ERROR "Repair script must verify profile registration state")
endif()

foreach(installed_script IN ITEMS repair_text refresh_text uninstall_text)
    if(NOT "${${installed_script}}" MATCHES "resolve-installed-dev\\.ps1" OR
       NOT "${${installed_script}}" MATCHES "Resolve-PiInputInstalledDev")
        message(FATAL_ERROR "Installed-development script does not use the shared active-version resolver")
    endif()
endforeach()
if(NOT resolver_text MATCHES "current\\.txt" OR NOT resolver_text MATCHES "InprocServer32" OR
   NOT resolver_text MATCHES "versions")
    message(FATAL_ERROR "Active-version resolver must validate current.txt and COM registration under versions")
endif()
if(refresh_text MATCHES "Stop-Process" OR NOT refresh_text MATCHES "PiInput-Install\\.exe")
    message(FATAL_ERROR "Refresh must use the side-by-side installer without force-closing applications")
endif()

if(NOT install_text MATCHES "Previous profile deactivation")
    message(FATAL_ERROR "Installer must treat previous profile cleanup as best effort")
endif()

if(text_service_text MATCHES "kPageSize = 5")
    message(FATAL_ERROR "TSF candidate paging must not return to the fixed five-item layout")
endif()

if(NOT text_service_text MATCHES "VK_OEM_MINUS" OR NOT text_service_text MATCHES "VK_OEM_PLUS")
    message(FATAL_ERROR "TSF must support minus/equal candidate paging")
endif()

if(NOT text_service_text MATCHES "toggle_input_mode")
    message(FATAL_ERROR "TSF must support standalone Shift input-mode switching")
endif()

if(NOT text_service_text MATCHES "punctuation_\\.transform")
    message(FATAL_ERROR "TSF Chinese input mode must route printable punctuation through PunctuationTransformer")
endif()

if(NOT candidate_window_text MATCHES "const int column" OR NOT candidate_window_text MATCHES "item_width")
    message(FATAL_ERROR "Candidate window must use horizontal column layout")
endif()

if(NOT cmake_text MATCHES "add_executable\\(PiInput-Install")
    message(FATAL_ERROR "CMake must build PiInput-Install.exe")
endif()
if(NOT installer_layout_text MATCHES "versions")
    message(FATAL_ERROR "Installer must use side-by-side version directories")
endif()
if(installer_text MATCHES "TerminateProcess" OR installer_text MATCHES "Stop-Process")
    message(FATAL_ERROR "Installer must not force-close user applications")
endif()
if(installer_text MATCHES "Dev[/\\\\]bin[/\\\\]PiInputTSF\\.dll")
    message(FATAL_ERROR "Installer must not overwrite the legacy fixed TSF DLL path")
endif()
if(NOT installer_text MATCHES "--silent")
    message(FATAL_ERROR "Installer must support silent integration verification")
endif()
if(NOT installer_text MATCHES "ERROR_PROC_NOT_FOUND")
    message(FATAL_ERROR "Missing DllRegisterServer must report ERROR_PROC_NOT_FOUND instead of a stale last-error value")
endif()
if(NOT installer_text MATCHES "DllUnregisterServer")
    message(FATAL_ERROR "A failed first installation must best-effort unregister a partially created TSF profile")
endif()
if(NOT setup_text MATCHES "PiInput-Install\\.exe" OR NOT setup_text MATCHES "--silent")
    message(FATAL_ERROR "setup-dev.ps1 must use the native side-by-side installer")
endif()

message(STATUS "Windows TSF source regression checks passed")
