cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR was not provided")
endif()

set(checksum_file "${SOURCE_DIR}/SHA256SUMS.txt")
if(NOT EXISTS "${checksum_file}")
    message(FATAL_ERROR "SHA256SUMS.txt is missing")
endif()

file(STRINGS "${checksum_file}" checksum_lines ENCODING UTF-8)
foreach(checksum_line IN LISTS checksum_lines)
    if(checksum_line STREQUAL "")
        continue()
    endif()
    if(NOT checksum_line MATCHES "^([0-9a-fA-F]+)  (.+)$")
        message(FATAL_ERROR "Invalid SHA256SUMS entry: ${checksum_line}")
    endif()
    set(expected_hash "${CMAKE_MATCH_1}")
    string(LENGTH "${expected_hash}" hash_length)
    if(NOT hash_length EQUAL 64)
        message(FATAL_ERROR "Invalid SHA256SUMS hash: ${checksum_line}")
    endif()
    set(relative_path "${CMAKE_MATCH_2}")
    string(REPLACE "\\" "/" relative_path "${relative_path}")
    if(relative_path STREQUAL "SHA256SUMS.txt")
        message(FATAL_ERROR "SHA256SUMS.txt must not hash itself")
    endif()
    if(relative_path MATCHES "^(build($|[-/])|dist($|/)|artifacts($|/)|\\.git($|/))")
        message(FATAL_ERROR "Generated path must not appear in SHA256SUMS.txt: ${relative_path}")
    endif()
    set(absolute_path "${SOURCE_DIR}/${relative_path}")
    if(NOT EXISTS "${absolute_path}" OR IS_DIRECTORY "${absolute_path}")
        message(FATAL_ERROR "SHA256SUMS entry does not name a file: ${relative_path}")
    endif()
    file(SHA256 "${absolute_path}" actual_hash)
    string(TOLOWER "${expected_hash}" expected_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "SHA256 mismatch: ${relative_path}")
    endif()
endforeach()

message(STATUS "SHA256SUMS integrity check passed")
